### ISSUE TITLE
[Bug]AttributeError 'PCB_SHAPE' object has no attribute 'GetAngle'

### ISSUE THREAD

**Issue by lukilukeskywalker** [ma-ha/kicad-laser-stencil-plugin#3]
Well, as said when trying to create the stencil gcode for this specific [project](https://github.com/lukilukeskywalker/TPSE) An error comes out saying PCB_SHAPE has no attribute GetAngle. I don't know what could be provoking this behaviour, but I am guessing it has to do something with the round corners or maybe the USB connector.
Pic of the error:
![Stencil_error](https://user-images.githubusercontent.com/26910841/166228987-ee1dd8c8-3627-4884-9b16-4b07655a8ce8.png)

**Comment by ma-ha** [comment]
Should work now with new parser - Sorry for late fixing

**Comment by Schluggi** [comment]
I got the same error on windows with Version v1.2:

![image](https://user-images.githubusercontent.com/43608073/211913853-25eebb92-5b36-4130-b98e-93259244d88e.png)

**Comment by ma-ha** [comment]
Can you perhaps attach or send me your PCB file?

**Comment by Schluggi** [comment]
> Can you perhaps attach or send me your PCB file?

Sure: https://github.com/Schluggi/AIOsense/releases/tag/v2.0-rc2

**Comment by ma-ha** [comment]
Thanks for the link: But I'm able to generate the stencil. All works fine.
Can you pls ensure that you use the most recent plugin v1.5.

**Comment by Schluggi** [comment]
Thank you. It works fine with v1.5. I just don't saw a release > v1.2. So i thought v1.2 was the latest version. My fault :)
